### ISSUE TITLE
Bug: section score is not calculated correctly

### ISSUE THREAD

**Issue by zagbc** [PoliNetworkOrg/TheTOLProject#104]
<img width="771" alt="Section score" src="https://github.com/PoliNetworkOrg/TheTOLProject/assets/92105630/6c80186f-14b0-4cfc-bc20-db6247e990b1">

**Comment by EndBug** [comment]
Hey, what's wrong with the calculation? Is it not +1 for every correct one, and -0,25 for every wrong one?

**Comment by zagbc** [comment]
The final score algorithm is correct. In fact, looking at the attached image: (1×0.33)+(1×2.6)+(1×3)+(1×2)=7.93

However, the section score should be respectively:

0.33
2.6
3
2

**Comment by EndBug** [comment]
It's by design: this way, you can see your score directly against the number of questions (which is directly to the right)
Having the section score already weighted would make this less intuitive

Do you find this way of presenting the result more confusing?

**Comment by zagbc** [comment]
Yep. For some freshmen it is not clear why the sum of the scores for each section is not equal to the final score.

**Comment by EndBug** [comment]
We could show both: we could put the weighted score as "Section score", and rename the current one as "Question points"/"Questions score", or something like that
What do you think?

**Comment by zagbc** [comment]
Imho, in this case less is more. I would leave the section score only.

**Comment by zagbc** [comment]
> It's by design: this way, you can see your score directly against the number of questions (which is directly to the right) Having the section score already weighted would make this less intuitive
> 
> Do you find this way of presenting the result more confusing?

You are right!!! Sorry to bother you, let's leave things as they are.

**Comment by EndBug** [comment]
<img src="https://i.imgur.com/ao0RAwq.gif">
