### ISSUE TITLE
chore: create a development preview

### ISSUE THREAD

**Issue by EndBug** [PoliNetworkOrg/TheTOLProject#12]
As of now, the only live version of the website is the production one: it would be useful, especially for non-developers, to have a live preview of the development version.
An idea would be using the GitHub pages deploy of this repo to host the development version (which would live in a separate branch as the stable one). It would also be nice to have an indicator to show that you're on the dev version of the website.

- [x] Update `deploy` workflow
- [x] Create new branch
- [x] #20

**Comment by zagbc** [comment]
Totally agree. It would be really helpful to have a live preview in order to both perform the required test and eventually get UI/UX suggestions from the project group members.
