### ISSUE TITLE
Images not displayed in 3 questions

### ISSUE THREAD

**Issue by zagbc** [PoliNetworkOrg/TheTOLProject#138]
The images related to questions [144], [145], and [147] are not displayed either in the prod database or in the simulation. 

Instead, they are present in the dev database used for the review.

![Image_db_question_144](https://github.com/PoliNetworkOrg/TheTOLProject/assets/92105630/5f4c7a9c-bb5e-406d-b626-6a4db4075d88)
![Image_sim_question_144](https://github.com/PoliNetworkOrg/TheTOLProject/assets/92105630/79554ac5-b86d-41ef-8427-8be033019fff)

![Image_db_question_145](https://github.com/PoliNetworkOrg/TheTOLProject/assets/92105630/4e979df6-98ad-4780-a782-dce86a7ce5fe)
![Image_sim_question_145](https://github.com/PoliNetworkOrg/TheTOLProject/assets/92105630/5b047ba1-f528-4574-ad78-beb08c14b4c0)
![Image_db_question_147](https://github.com/PoliNetworkOrg/TheTOLProject/assets/92105630/2eab6e74-9c17-4432-bee3-f401d47a27e1)
![Image_sim_question_147](https://github.com/PoliNetworkOrg/TheTOLProject/assets/92105630/a04c3bdf-83e4-4583-90ad-19f5bd4a9896)

**Comment by lorenzocorallo** [comment]
I think this can be closed. @zagbc

**Comment by zagbc** [comment]
This issue was related to https://github.com/PoliNetworkOrg/TheTOLProjectData/pull/3
