### ISSUE TITLE
Bug: correctly handle browser back button usage

### ISSUE THREAD

**Issue by EndBug** [PoliNetworkOrg/TheTOLProject#26]
As of now, going back to the previous page when in the results screen correctly redirects to home, but when you start the test you skip directly to the last section, and you can edit your answers

**Comment by lorenzocorallo** [comment]
Hi there, what's the stage on this one? Have things changed since this issue was opened?

**Comment by EndBug** [comment]
@lorenzocorallo No, I don't think there has been any change, do you want to take this over?

**Comment by EndBug** [comment]
Well, we patched the issue by removing history entries entirely.
The problem with that is that if you go, for example, to "About", then "Home", and then you want to go back you won't be able to. 

Ideally we would be able to keep every history entry, but if you try to navigate back to any "test" page you get sent back to the homepage
