### ISSUE TITLE
Radio buttons misaligned

### ISSUE THREAD

**Issue by zagbc** [PoliNetworkOrg/TheTOLProject#33]
Using a mobile phone, the radio buttons to select the answer are not aligned with the letters that mark them nor with the texts of the questions themselves. This happens when the phone is in the upright position, that is, when the answer texts are not on the same line.

![Radio buttons](https://user-images.githubusercontent.com/92105630/189430939-b36e18b7-38d1-4870-a287-91719baa2329.jpg)

**Comment by EndBug** [comment]
Can reproduce ✅
