### ISSUE TITLE
Bug: correctly display linked images on Firefox mobile

### ISSUE THREAD

**Issue by zagbc** [PoliNetworkOrg/TheTOLProject#34]
Using Firefox mobile 104.1.0 , images linked to questions are partially displayed.

![Firefox mobile](https://user-images.githubusercontent.com/92105630/189434616-6ce1c7ea-9e7d-4515-946c-2a8d32082a55.jpg)

Please note that even on Firefox desktop 104.0.2 the images appear stretched. However, in this case they can be fully displayed.

<img width="2048" alt="Firefox desktop" src="https://user-images.githubusercontent.com/92105630/189434727-733ab35a-49b9-485f-bc09-37251f37655e.png">

**Comment by EndBug** [comment]
I can reproduce the issue on these browsers:
- Firefox 104 on Windows 11
- Safari 15.3 on macOS Monterey
- Firefox 104 on macOS Monterey
- Safari on iOS 15
- Firefox on Android 12

Seems like it's an issue with flexbox rendering on non-Chromium-based browsers.
