### ISSUE TITLE
Bug: saving simulation results on Firefox mobile

### ISSUE THREAD

**Issue by zagbc** [PoliNetworkOrg/TheTOLProject#35]
Using Firefox mobile 104.1.0, it is not possible to save the results at the end of the simulation (pdf file).

**Comment by toto04** [comment]
Tested this on iOS 16 Firefox 104.2 and everything works correctly, but that's to be expected since as far as I know all browsers on iOS are required to use Apple's webkit, every browser on an iPhone should behave as if it was Safari.

**Comment by EndBug** [comment]
Alright, thanks ;)

**Comment by lorenzocorallo** [comment]
Fix WIP (https://github.com/lorenzocorallo/TheTOLProject/tree/35-saving-simulation-results)
