### ISSUE TITLE
Meta: improve SEO

### ISSUE THREAD

**Issue by bob27aggiustatutto** [PoliNetworkOrg/TheTOLProject#45]
Improve SEO to rank up in search results from multiple search engines

(old issue #43)

**Comment by zagbc** [comment]
Now our web app has been ranking very well for several months. I'm using the string "simulatore tol" with the 3 major search engines and here are the results: 

Google: no 1 
Bing: no 1 
Yahoo: no 1

That is, without having implemented a robust SEO strategy. I'm going to close this issue, please let me know if you want to proceed differently.
