### ISSUE TITLE
Make the tool accessible to students with special needs

### ISSUE THREAD

**Issue by EndBug** [PoliNetworkOrg/TheTOLProject#48]
Students with dyslexia and other special needs may have different longer times to complete the test.

A user has reported that, since they're dyslexic, their test will have:
- 20 more minutes for MAT
- 10 more minutes for ING
- 10 more minutes for COM
- 10 more minutes for FIS

We still have to check if there are any guidelines in place or if the times are decided on a case-to-case basis.

**Comment by lorenzocorallo** [comment]
From the call for application 2023/24:
> Per motivi organizzativi i candidati con disabilità e/o con diagnosi di disturbi specifici dell’apprendimento (DSA) devono segnalare la loro richiesta di ausili e/o maggiorazione del tempo in fase di iscrizione al test entro e non oltre 48 ore prima della chiusura delle iscrizioni. 
>
> Il servizio Pari Opportunità – Multi Chance Poli Team del Politecnico contatta i candidati con disabilità per verificare le certificazioni cliniche o di invalidità in loro possesso, e valutare le loro esigenze specifiche per concordare le modalità di svolgimento delle prove di cui al presente bando in conformità alla L.104/1992 e successive modificazioni.
> [...]

It seems that modifications are made case-to-case depending on the particular needs.
If any member of the "Pari Opportunità - Multi Change Poli Team" could give some sort of table where additional times are described, then it could be implemented.
Otherwise the only option is to give the user the possibility to customize the test based on his needs, giving default parameters (maybe this customization can be reported on the results PDF).

**Comment by EndBug** [comment]
Yeah, that's what we thought: we were planning on sending them an email through the association channels but I don't think this has been done.
I honestly would go for adding a customizable time menu either way, but it would be nice if the default values were as accurate as possible

**Comment by zagbc** [comment]
The rules reported by the student with DSA are not those provided by PoliMi. The student later reported that these were only his expectations. 

Based on the official DSA rules received from PoliMI (multichance team), students with DSA are allowed 30% extra time.
A summary of what was decided at the last follow-up meeting could be what you find attached. The layout is just a proposal, feel free to consider any better solution.
<img width="393" alt="DSA" src="https://user-images.githubusercontent.com/92105630/223671097-3353feef-b9bf-47fb-afa4-af5c32d23ffe.PNG">
