### ISSUE TITLE
Feat: Question Browser

### ISSUE THREAD

**Issue by lorenzocorallo** [PoliNetworkOrg/TheTOLProject#52]
Hi everyone,
this is to propose a new feature: "Question Browser".
I've bene using the TOL project 
 for a while and I'm in the Telegram group where solutions are posted and discussed; I saw that it ends up making tons of screenshot of questions while making the test because "I want to post it later on", caused by the fact that the result pdf produced at the end only includes the prompt and the wrong (if any) + correct choice, which will make incomplete the question when posted.
Moreover, sometimes you may want to try solving an exercise you didn't get right and you want to have all the options besides the correct one immediately (which doesn't reflect what happens in tests).
Until now, I've been checking out the [database.json](https://raw.githubusercontent.com/PoliNetworkOrg/TheTOLProjectData/main/database.json) which gives all the options of all the questions, but in this case the correct option is shown; so the real alternative is doing screenshots, but it's a waste of time (even if little) during the test; besides that, you may not take screenshot of a question you decide to check later on.
The feature I propose "extends" something that already exists in this repo, which is the `dbpreview` route.
At the time being, this is a partially hidden route to check (I assume) if the database is correctly loaded and which questions are.
It's divided into the 4 test sections which you can click-to-open and get all the questions listed ordered by id with the prompt, the options and an arrow pointing the correct one.
These are the main points of my idea:

- Show all the questions together
- Create a tool topbar including:
  - filter by text search 
  - filter by section (eng, mat...): switch buttons, maybe plain checkbox if design stack requires to use plain html, which are multi-selectable (you can see math and physics together)
  - switch to show correct options (TBD adding this type of switch to every question acting locally on the single one)
- button which copies in clipboard an image of the question with the options (not including the correct one)
- other features can be proposed.

This post is to collect other users thoughts  and, of course, maintainers ones.
Hope this doesn’t break any main concept of the application, I didn’t find anything on the repo defining main goals or restrictions. 
I’m available to actively develop this feature if it gets approved.
Feel free to post any thought.

**Comment by zagbc** [comment]
Hi Lorenzo, we really appreciate your interest in this project, thanks! We have a preview version of the database that partially contains the suggested functionality. The main purpose of the database is to provide a preview of the created questions to facilitate the validation process by the project team. We would prefer to keep the database as a tool for internal use.
