### ISSUE TITLE
Add footer when taking test

### ISSUE THREAD

**Issue by bob27aggiustatutto** [PoliNetworkOrg/TheTOLProject#85]
![immagine](https://user-images.githubusercontent.com/120955097/234012316-b3746d48-f879-41a2-a127-ac021b025363.png)

add footer

**Comment by lorenzocorallo** [comment]
@EndBug it was decided to not show Footer during test, should we add it back?

**Comment by zagbc** [comment]
Confirmed. No footer during the test, they MUST be hidle.
