### ISSUE TITLE
Question navigation during test is broken

### ISSUE THREAD

**Issue by EndBug** [PoliNetworkOrg/TheTOLProject#93]
Some of the previous PRs borke the question navigation: if you try to change the question by clicking on the number the page goes back to the homepage.

**Comment by EndBug** [comment]
`git bisect` shows that the firsy bad commit is 6dbd3cf31df30da4b9a2c15670efcc5217100253, the merge commit of pr #81

**Comment by EndBug** [comment]
@lorenzocorallo Is there a way we can fix this? Can you look into it?

**Comment by lorenzocorallo** [comment]
I had already opened PR #91 which fixes the bug, if I understood correctly what you are reporting

**Comment by EndBug** [comment]
Yeah, that was it, thanks 👍🏻
